### ISSUE TITLE
feat: add jcaigitlab/asdf-git

### ISSUE THREAD

**Issue by D-Bhatta** [mise-plugins/registry#32]
## What I want

Please revert [remove asdf-git ](https://github.com/mise-plugins/registry/commit/b445902557ba51191969afb343b92677409d24bd) and add plugin for git to registry.

## Reason

I use [this git plugin](https://gitlab.com/jcaigitlab/asdf-git) in mise on *nix machines, along with the `all_compile = true` setting, to compile newer versions of git than what comes with the distribution. The benefits are:

- Ease of administration, especially on remote machines. One `mise install` gets me a full dev environment everytime.
- Using `git@latest` ensures I encounter the exact same version of git across all machines, all with exact same behavior. This allows full automation of configuration, with no expected differences in behavior across machines. I just copy config files from a remote, and that's it.
- Makes git administration much easier in environments such as WSL2 boxes, where git administration used to be a major pain point. Now it's just `mise install` and some `cp` commands to copy configuration files.

## Workarounds

I manually injected this plugin on my latest install with `mise plugins install git https://gitlab.com/jcaigitlab/asdf-git.git` when I got a `No repository found for plugin git` error, but the added overhead makes the experience tedious for a bit.

I now have to remember to install this plugin manually, instead of having it in my `config.toml` file and just using `mise install` to set up an environment on a new machine.

___

I think including a git plugin will make the experience of using mise much better and smoother.

I am happy to write a PR myself if approved.

**Comment by jdx** [comment]
git is a prerequisite for using mise, it does not make sense to make it available as a plugin and doing so will result in an infinite loop for plugins that call git when using shims, so no, I won't be considering putting it back in
